- name: "NOTSCORED | 6.1.1 | PATCH | Audit system file permissions"
  command: rpm -Va --nomtime --nosize --nomd5 --nolinkto
  changed_when: no
  failed_when: no
  register: section_6_1_1
  when:
      - rhel7cis_rule_6_1_1
  tags:
      - level2
      - patch
      - rule_6.1.1

- name: "SCORED | 6.1.2 | PATCH | Ensure permissions on /etc/passwd are configured"
  file:
      dest: /etc/passwd
      owner: root
      group: root
      mode: 0644
  when:
      - rhel7cis_rule_6_1_2
  tags:
      - level1
      - level2
      - patch
      - rule_6.1.2

- name: "SCORED | 6.1.3 | PATCH | Ensure permissions on /etc/shadow are configured"
  file:
      dest: /etc/shadow
      owner: root
      group: root
      mode: 0000
  when:
      - rhel7cis_rule_6_1_3
  tags:
      - level1
      - level2
      - patch
      - rule_6.1.3

- name: "SCORED | 6.1.4 | PATCH | Ensure permissions on /etc/group are configured"
  file:
      dest: /etc/group
      owner: root
      group: root
      mode: 0644
  when:
      - rhel7cis_rule_6_1_4
  tags:
      - level1
      - level2
      - patch
      - rule_6.1.4

- name: "SCORED | 6.1.5 | PATCH | Ensure permissions on /etc/gshadow are configured"
  file:
      dest: /etc/gshadow
      owner: root
      group: root
      mode: 0000
  when:
      - rhel7cis_rule_6_1_5
  tags:
      - level1
      - level2
      - patch
      - rule_6.1.5

- name: "SCORED | 6.1.6 | PATCH | Ensure permissions on /etc/passwd- are configured"
  file:
      dest: /etc/passwd-
      owner: root
      group: root
      mode: 0600
  when:
      - rhel7cis_rule_6_1_6
  tags:
      - level1
      - level2
      - patch
      - rule_6.1.6

- name: "SCORED | 6.1.7 | PATCH | Ensure permissions on /etc/shadow- are configured"
  file:
      dest: /etc/shadow-
      owner: root
      group: root
      mode: 0000
  when:
      - rhel7cis_rule_6_1_7
  tags:
      - level1
      - level2
      - patch
      - rule_6.1.7

- name: "SCORED | 6.1.8 | PATCH | Ensure permissions on /etc/group- are configured"
  file:
      dest: /etc/group-
      owner: root
      group: root
      mode: 0644
  when:
      - rhel7cis_rule_6_1_8
  tags:
      - level1
      - level2
      - patch
      - rule_6.1.8

- name: "SCORED | 6.1.9 | PATCH | Ensure permissions on /etc/gshadow- are configured"
  file:
      dest: /etc/gshadow-
      owner: root
      group: root
      mode: 0000
  when:
      - rhel7cis_rule_6_1_9
  tags:
      - level1
      - level2
      - patch
      - rule_6.1.9

- name: "SCORED | 6.1.10 | PATCH | Ensure no world writable files exist"
  shell: "df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f -perm -0002"
  register: section_6_1_10
  when:
      - rhel7cis_rule_6_1_10
  tags:
      - level1
      - level2
      - patch
      - rule_6.1.10

- name: "SCORED | 6.1.11 | PATCH | Ensure no unowned files or directories exist"
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -nouser
  register: section_6_1_11
  when:
      - rhel7cis_rule_6_1_11
  tags:
      - level1
      - level2
      - patch
      - rule_6.1.11
      - command

- name: "SCORED | 6.1.12 | PATCH | Ensure no ungrouped files or directories exist"
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -nogroup
  register: section_6_1_12
  when:
      - rhel7cis_rule_6_1_12
  tags:
      - level1
      - level2
      - patch
      - rule_6.1.12
      - command

- name: "NOTSCORED | 6.1.13 | PATCH | Audit SUID executables"
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f -perm -4000
  register: section_6_1_13
  when:
      - rhel7cis_rule_6_1_13
  tags:
      - level1
      - level2
      - patch
      - rule_6.1.13
      - command

- name: "NOTSCORED | 6.1.14 | PATCH | Audit SGID executables"
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f -perm -2000
  register: section_6_1_14
  when:
      - rhel7cis_rule_6_1_14
  tags:
      - level1
      - level2
      - patch
      - rule_6.1.14
      - command

- name: "SCORED | 6.2.1 | PATCH | Ensure password fields are not empty"
  command: passwd -l {{ item }}
  changed_when: no
  failed_when: no
  with_items: "{{ empty_password_accounts.stdout_lines }}"
  when:
      - empty_password_accounts.rc
      - rhel7cis_rule_6_2_1
  tags:
      - level1
      - level2
      - patch
      - rule_6.2.1

- name: "SCORED | 6.2.2 | PATCH | Ensure no legacy '+' entries exist in /etc/passwd"
  command: sed -i '/^+/ d' /etc/passwd
  changed_when: no
  failed_when: no
  when:
      - rhel7cis_rule_6_2_2
  tags:
      - level1
      - level2
      - patch
      - rule_6.2.2

- name: "SCORED | 6.2.3 | PATCH | Ensure no legacy '+' entries exist in /etc/shadow"
  command: sed -i '/^+/ d' /etc/shadow
  changed_when: no
  failed_when: no
  when:
      - rhel7cis_rule_6_2_3
  tags:
      - level1
      - level2
      - patch
      - rule_6.2.3

- name: "SCORED | 6.2.4 | PATCH | Ensure no legacy '+' entries exist in /etc/group"
  command: sed -i '/^+/ d' /etc/group
  changed_when: no
  failed_when: no
  when:
      - rhel7cis_rule_6_2_4
  tags:
      - level1
      - level2
      - patch
      - rule_6.2.4

- name: "SCORED | 6.2.5 | PATCH | Ensure root is the only UID 0 account"
  command: passwd -l {{ item }}
  changed_when: no
  failed_when: no
  with_items: "{{ uid_zero_accounts_except_root.stdout_lines }}"
  when:
      - uid_zero_accounts_except_root.rc
      - rhel7cis_rule_6_2_5
  tags:
      - level1
      - level2
      - patch
      - rule_6.2.5

- name: "SCORED | 6.2.6 | PATCH | Ensure root PATH Integrity"
  command: sed -i --follow-symlinks '/PATH/ s/^/#/g' /root/.bash_profile
  when: rhel7cis_rule_6_2_6
  tags:
      - level1
      - level2
      - patch
      - rule_6.2.6

- name: "SCORED | 6.2.6 | PATCH | Ensure root PATH Integrity"
  script: files/6_2_6.sh
  register: section_6_2_6
  when: rhel7cis_rule_6_2_6
  tags:
      - level1
      - level2
      - patch
      - rule_6.2.6

- name: "SCORED | 6.2.7 | PATCH | Ensure all users' home directories exist"
  script: files/6_2_7.sh
  register: section_6_2_7
  when: rhel7cis_rule_6_2_7
  tags:
      - level1
      - level2
      - patch
      - rule_6.2.7

- debug:
    var: section_6_2_7
  when: rhel7cis_rule_6_2_7
  tags:
      - level1
      - level2
      - patch
      - rule_6.2.7

- name: "SCORED | 6.2.7 | PATCH | Ensure all users' home directories exist"
  user:
    name: "{{ item.split(':')[0] }}"
    home: "{{ item.split(':')[1] }}"
  with_items: "{{ section_6_2_7.stdout_lines }}"
  when:
      - rhel7cis_rule_6_2_7
      - section_6_2_7.stdout_lines is defined and section_6_2_7.stdout_lines|length > 1
  tags:
      - level1
      - level2
      - patch
      - rule_6.2.7

- name: "SCORED | 6.2.8 | PATCH | Ensure users' home directories permissions are 750 or more restrictive"
  script: files/6_2_8.sh
  register: section_6_2_8
  when: rhel7cis_rule_6_2_8
  tags:
      - level1
      - level2
      - patch
      - rule_6.2.8

- name: "SCORED | 6.2.9 | PATCH | Ensure users own their home directories"
  script: files/6_2_9.sh
  register: section_6_2_9
  when: rhel7cis_rule_6_2_9
  tags:
      - level1
      - level2
      - patch
      - rule_6.2.9

- name: "SCORED | 6.2.9 | PATCH | Ensure users own their home directories"
  file:
    owner: "{{ item.split(':')[1] }}"
    path: "{{ item.split(':')[0] }}"
    state: directory
    follow: yes
  with_items: "{{ section_6_2_9.stdout_lines }}"
  when:
      - rhel7cis_rule_6_2_9
      - section_6_2_9.stdout_lines is defined and section_6_2_9.stdout_lines|length > 1
  tags:
      - level1
      - level2
      - patch
      - rule_6.2.9

- name: "SCORED | 6.2.10 | PATCH | Ensure users' dot files are not group or world writable"
  script: files/6_2_10.sh
  register: section_6_2_10
  when: rhel7cis_rule_6_2_10
  tags:
      - level1
      - level2
      - patch
      - rule_6.2.10

- name: "SCORED | 6.2.11 | PATCH | Ensure no users have .forward files"
  file:
      state: absent
      dest: "~{{ item }}/.forward"
  with_items: "{{ users.stdout_lines }}"
  when:
      - rhel7cis_rule_6_2_11
  tags:
      - level1
      - level2
      - patch
      - rule_6.2.11

- name: "SCORED | 6.2.12 | PATCH | Ensure no users have .netrc files"
  file:
      state: absent
      dest: "~{{ item }}/.netrc"
  with_items: "{{ users.stdout_lines }}"
  when:
      - rhel7cis_rule_6_2_12
  tags:
      - level1
      - level2
      - patch
      - rule_6.2.12

- name: "SCORED | 6.2.13 | PATCH | Ensure users netrc Files are not group or world accessible"
  script: files/6_2_13.sh
  register: section_6_2_13
  when: rhel7cis_rule_6_2_13
  tags:
      - level1
      - level2
      - patch
      - rule_6.2.13

- name: "SCORED | 6.2.14 | PATCH | Ensure no users have .rhosts files"
  file:
      state: absent
      dest: "~{{ item }}/.rhosts"
  with_items: "{{ users.stdout_lines }}"
  when:
      - rhel7cis_rule_6_2_14
  tags:
      - level1
      - level2
      - patch
      - rule_6.2.14

- name: "SCORED | 6.2.15 | PATCH | Ensure all groups in /etc/passwd exist in /etc/group"
  script: files/6_2_15.sh
  register: section_6_2_15
  when: rhel7cis_rule_6_2_15
  tags:
      - level1
      - level2
      - patch
      - rule_6.2.15

- name: "SCORED | 6.2.16 | PATCH | Ensure no duplicate UIDs exist"
  script: files/6_2_16.sh
  register: section_6_2_16
  when: rhel7cis_rule_6_2_16
  tags:
      - level1
      - level2
      - patch
      - rule_6.2.16

- name: "SCORED | 6.2.17 | PATCH | Ensure no duplicate GIDs exist"
  script: files/6_2_17.sh
  register: section_6_2_17
  when: rhel7cis_rule_6_2_17
  tags:
      - level1
      - level2
      - patch
      - rule_6.2.17

- name: "SCORED | 6.2.18 | PATCH | Ensure no duplicate user names exist"
  script: files/6_2_18.sh
  register: section_6_2_18
  when: rhel7cis_rule_6_2_18
  tags:
      - level1
      - level2
      - patch
      - rule_6.2.18

- name: "SCORED | 6.2.19 | PATCH | Ensure no duplicate group names exist"
  script: files/6_2_19.sh
  register: section_6_2_19
  when: rhel7cis_rule_6_2_19
  tags:
      - level1
      - level2
      - patch
      - rule_6.2.19
