---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
#    instance_type: t2.micro
#    security_group: launch_wizard-6
#    image: ami-036affea69a1101c9
#    keypair: ansible
    region: us-west-2
#    count: 1
#    aws_pem: aws/aws_ansible.pem

#    instance_tags_Name: redhat03
    instance_tags_Type: webserver

  vars_files:
    - aws/aws_keys.yml

  tasks:
    - block:

      - name: Gather facts for target group
        ec2_instance_facts:
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          region: "{{ region }}"
#          filters:
#            "tag:Type": "{{ instance_tags_Type }}"
        register: ec2_group_facts

#      - debug:
#          msg: "{{ ec2_group_facts | json_query('instances[*].{Name: tags.Name, Status: state.name, IP: private_ip_address}') | join(', ') }}"

      - name: POST contents
        uri:
          url: <<>>
          method: POST
          force_basic_auth: yes
          status_code: 201
          body: "{{ ec2_group_facts | json_query('instances[*].{Name: tags.Name, Status: state.name, IP: private_ip_address}') | join(', ') }}"
          body_format: json
