<<<<<<< HEAD
- hosts: localhost
=======
- hosts: local
>>>>>>> 3f966b7faf427ebb6c10a699ce85aba9eb0b2ddc
  connection: local
  vars:
    region: us-west-2
  vars_files:
<<<<<<< HEAD
    - aws/aws_keys.yml
=======
    - aws_keys.yml
>>>>>>> 3f966b7faf427ebb6c10a699ce85aba9eb0b2ddc
  tasks:
    - name: Gather EC2 facts
      ec2_instance_facts:
        region: "{{ region }}"
        filters:
          "tag:Type": "webserver"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: ec2
    - debug: var=ec2

    - name: Terminate EC2 Instance(s)
      ec2:
        instance_ids: '{{ item.instance_id }}'
        state: absent
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      with_items: "{{ ec2.instances }}"
