ansible_user: ansible
ansible_password: pcphkP@ssw0rd1
ansible_connection: winrm
ansible_winrm_transport: basic
ansible_winrm_scheme: http
ansible_winrm_server_cert_validation: ignore
ansible_port: 5985
